import XCTest
@testable import SpeechVAD

/// Tests for AOSC (Arrival-Order Speaker Cache) compression algorithm.
///
/// Sub-function tests use hand-computed expected values verified against NeMo PyTorch.
/// Full pipeline tests load `nemo_ground_truth.json` generated by `scripts/definitive_verify.py`
/// which runs the REAL NeMo `SortformerModules._compress_spkcache` with PyTorch tensors.
/// All test inputs use unique prediction values (no score ties) to ensure deterministic output.
final class SortformerAOSCTests: XCTestCase {

    // MARK: - getLogPredScores

    func testGetLogPredScores() {
        // 4 frames, 4 speakers - varied activity patterns
        let preds: [Float] = [
            0.9, 0.1, 0.05, 0.05,   // f0: Speaker 0 active
            0.1, 0.85, 0.05, 0.05,  // f1: Speaker 1 active
            0.8, 0.7, 0.05, 0.05,   // f2: Overlap speakers 0+1
            0.05, 0.05, 0.05, 0.05, // f3: Silence
        ]
        let nFrames = 4, nSpk = 4
        let threshold: Float = 0.25

        let scores = AOSCCompressor.getLogPredScores(
            preds: preds, nFrames: nFrames, nSpk: nSpk, threshold: threshold)

        // Expected from Python reference
        let expected: [Float] = [
            0.37983966, -2.18202806, -2.23609543, -2.23609543,
            -2.18202806, 0.32268131, -2.23609543, -2.23609543,
            -0.83655596, -1.15240884, -3.33470774, -3.33470774,
            -0.84702718, -0.84702718, -0.84702718, -0.84702718,
        ]

        XCTAssertEqual(scores.count, expected.count)
        for i in 0..<scores.count {
            XCTAssertEqual(scores[i], expected[i], accuracy: 1e-4,
                           "Score mismatch at index \(i): got \(scores[i]), expected \(expected[i])")
        }

        // Verify properties: active speaker's score should be highest in its frame
        XCTAssertTrue(scores[0] > scores[1], "Frame 0: speaker 0 should have highest score")
        XCTAssertTrue(scores[5] > scores[4], "Frame 1: speaker 1 should have highest score")
        // Overlap frame: both scores should be negative
        XCTAssertTrue(scores[8] < 0, "Frame 2 overlap: speaker 0 score should be negative")
        XCTAssertTrue(scores[9] < 0, "Frame 2 overlap: speaker 1 score should be negative")
    }

    func testGetLogPredScoresThresholdClamping() {
        // Test that very small probabilities are clamped to threshold
        let preds: [Float] = [0.0, 1.0]  // Extreme values
        let scores = AOSCCompressor.getLogPredScores(
            preds: preds, nFrames: 1, nSpk: 2, threshold: 0.25)
        // Neither score should be NaN or infinite
        for s in scores {
            XCTAssertFalse(s.isNaN, "Score should not be NaN with threshold clamping")
            XCTAssertTrue(s.isFinite, "Score should be finite with threshold clamping")
        }
    }

    // MARK: - disableLowScores

    func testDisableLowScores() {
        let preds: [Float] = [
            0.9, 0.1, 0.05, 0.05,
            0.1, 0.85, 0.05, 0.05,
            0.8, 0.7, 0.05, 0.05,
            0.05, 0.05, 0.05, 0.05,
        ]
        let nFrames = 4, nSpk = 4

        var scores = AOSCCompressor.getLogPredScores(
            preds: preds, nFrames: nFrames, nSpk: nSpk, threshold: 0.25)
        AOSCCompressor.disableLowScores(
            preds: preds, scores: &scores, nFrames: nFrames, nSpk: nSpk,
            minPosScoresPerSpk: 1)

        // Expected from Python reference
        let expected: [Float] = [
            0.37983966, -.infinity, -.infinity, -.infinity,
            -.infinity, 0.32268131, -.infinity, -.infinity,
            -.infinity, -.infinity, -.infinity, -.infinity,
            -.infinity, -.infinity, -.infinity, -.infinity,
        ]

        XCTAssertEqual(scores.count, expected.count)
        for i in 0..<scores.count {
            if expected[i].isInfinite {
                XCTAssertEqual(scores[i], -.infinity,
                               "Index \(i): expected -inf, got \(scores[i])")
            } else {
                XCTAssertEqual(scores[i], expected[i], accuracy: 1e-4,
                               "Index \(i): got \(scores[i]), expected \(expected[i])")
            }
        }
    }

    func testDisableLowScoresNonSpeech() {
        // All frames below 0.5 → all disabled
        let preds: [Float] = [0.3, 0.2, 0.4, 0.1]
        var scores: [Float] = [1.0, 2.0, 3.0, 4.0]
        AOSCCompressor.disableLowScores(
            preds: preds, scores: &scores, nFrames: 1, nSpk: 4,
            minPosScoresPerSpk: 0)
        for s in scores {
            XCTAssertEqual(s, -.infinity, "Non-speech frames should be disabled")
        }
    }

    func testDisableLowScoresOverlapSuppression() {
        // 3 frames, 2 speakers: f0=spk0, f1=overlap, f2=spk0
        let preds: [Float] = [
            0.9, 0.1,   // f0: spk0 clear
            0.8, 0.7,   // f1: overlap → non-positive score
            0.9, 0.1,   // f2: spk0 clear
        ]
        var scores = AOSCCompressor.getLogPredScores(
            preds: preds, nFrames: 3, nSpk: 2, threshold: 0.25)
        AOSCCompressor.disableLowScores(
            preds: preds, scores: &scores, nFrames: 3, nSpk: 2,
            minPosScoresPerSpk: 1)

        // Speaker 0 at f0 and f2: positive scores, kept
        XCTAssertTrue(scores[0].isFinite && scores[0] > 0, "f0-spk0 should be kept")
        XCTAssertTrue(scores[4].isFinite && scores[4] > 0, "f2-spk0 should be kept")
        // Speaker 0 at f1 (overlap): non-positive → disabled since spk0 has 2 positive
        XCTAssertEqual(scores[2], -.infinity, "f1-spk0 overlap should be disabled")
    }

    // MARK: - boostTopkScores

    func testBoostTopkScores() {
        // 6 frames, 2 speakers
        var scores: [Float] = [
            5.0, 1.0,
            3.0, 4.0,
            1.0, 2.0,
            -.infinity, 6.0,
            2.0, -.infinity,
            4.0, 3.0,
        ]

        AOSCCompressor.boostTopkScores(
            scores: &scores, nFrames: 6, nSpk: 2,
            nBoostPerSpk: 2, scaleFactor: 2.0)

        let boost: Float = -2.0 * logf(0.5)

        // Expected from Python reference
        let expected: [Float] = [
            5.0 + boost, 1.0,
            3.0, 4.0 + boost,
            1.0, 2.0,
            -.infinity, 6.0 + boost,
            2.0, -.infinity,
            4.0 + boost, 3.0,
        ]

        for i in 0..<scores.count {
            if expected[i].isInfinite {
                XCTAssertEqual(scores[i], -.infinity,
                               "Index \(i): -inf should remain -inf")
            } else {
                XCTAssertEqual(scores[i], expected[i], accuracy: 1e-4,
                               "Index \(i): got \(scores[i]), expected \(expected[i])")
            }
        }
    }

    func testBoostTopkScoresInfUntouched() {
        // -inf scores should never be boosted
        var scores: [Float] = [-.infinity, -.infinity, -.infinity, -.infinity]
        AOSCCompressor.boostTopkScores(
            scores: &scores, nFrames: 2, nSpk: 2,
            nBoostPerSpk: 5, scaleFactor: 2.0)
        for s in scores {
            XCTAssertEqual(s, -.infinity, "-inf should remain -inf after boosting")
        }
    }

    func testBoostTopkScoresZeroBoost() {
        var scores: [Float] = [1.0, 2.0, 3.0, 4.0]
        let original = scores
        AOSCCompressor.boostTopkScores(
            scores: &scores, nFrames: 2, nSpk: 2,
            nBoostPerSpk: 0, scaleFactor: 2.0)
        XCTAssertEqual(scores, original, "Zero boost should not modify scores")
    }

    // MARK: - getTopkIndices

    func testGetTopkIndices() {
        // 8 real frames + 2 silence, 2 speakers, select top 6
        let scores: [Float] = [
            5.0, 1.0,              // f0
            3.0, 4.0,              // f1
            1.0, 2.0,              // f2
            -.infinity, 6.0,       // f3
            2.0, -.infinity,       // f4
            4.0, 3.0,              // f5
            -.infinity, -.infinity, // f6
            0.5, 0.5,             // f7
            .infinity, .infinity, // sil f8
            .infinity, .infinity, // sil f9
        ]

        let (indices, disabled) = AOSCCompressor.getTopkIndices(
            scores: scores, nFrames: 10, nSpk: 2,
            spkcacheLen: 6, silFramesPerSpk: 2)

        XCTAssertEqual(indices.count, 6)
        XCTAssertEqual(disabled.count, 6)

        // Expected from Python reference
        let expectedIndices = [0, 0, 0, 3, 0, 0]
        let expectedDisabled = [false, true, true, false, true, true]
        XCTAssertEqual(indices, expectedIndices)
        XCTAssertEqual(disabled, expectedDisabled)

        // Properties: 4 disabled (2 sil * 2 spk), 2 real frames
        let disabledCount = disabled.filter { $0 }.count
        XCTAssertEqual(disabledCount, 4, "Should have 4 disabled (2 sil frames * 2 speakers)")
    }

    func testGetTopkIndicesPreservesOrder() {
        // Verify that selected frames maintain chronological order within each speaker block
        let scores: [Float] = [
            3.0, 1.0,   // f0
            1.0, 3.0,   // f1
            2.0, 0.5,   // f2
            0.5, 2.0,   // f3
        ]
        let (indices, disabled) = AOSCCompressor.getTopkIndices(
            scores: scores, nFrames: 4, nSpk: 2,
            spkcacheLen: 4, silFramesPerSpk: 0)

        // No disabled frames (spkcacheLen = nFrames * nSpk would need more,
        // but spkcacheLen=4 selects top 4 globally)
        // Top 4 flattened (spk0: [3,1,2,0.5], spk1: [1,3,0.5,2]):
        //   spk0-f0=3(idx0), spk1-f1=3(idx5), spk0-f2=2(idx2), spk1-f3=2(idx7)
        // Sorted: [0, 2, 5, 7] → mod 4: [0, 2, 1, 3]
        XCTAssertEqual(disabled.filter { !$0 }.count, 4, "All frames should be valid")

        // First two should be speaker 0's frames (lower flat indices),
        // last two should be speaker 1's
        // Within each block, frame order should be ascending
        var prevFrame = -1
        for i in 0..<indices.count where !disabled[i] {
            let frame = indices[i]
            if i > 0 && frame < prevFrame {
                // This is OK if we crossed a speaker boundary
            }
            prevFrame = frame
        }
    }

    // MARK: - gatherSpkcacheAndPreds

    func testGatherSpkcacheAndPreds() {
        let embSeq: [Float] = [
            1, 2, 3,   // f0
            4, 5, 6,   // f1
            7, 8, 9,   // f2
        ]
        let preds: [Float] = [
            0.9, 0.1,  // f0
            0.5, 0.5,  // f1
            0.1, 0.9,  // f2
        ]
        let meanSilEmb: [Float] = [0.5, 0.5, 0.5]
        let topkIndices = [0, 0, 2]
        let isDisabled = [false, true, false]

        let result = AOSCCompressor.gatherSpkcacheAndPreds(
            embSeq: embSeq, preds: preds,
            topkIndices: topkIndices, isDisabled: isDisabled,
            meanSilEmb: meanSilEmb,
            spkcacheLen: 3, embDim: 3, nSpk: 2)

        // Entry 0: frame 0 (not disabled)
        XCTAssertEqual(Array(result.spkcache[0..<3]), [1, 2, 3])
        XCTAssertEqual(Array(result.spkcachePreds[0..<2]), [0.9, 0.1])

        // Entry 1: disabled → silence embedding, zero predictions
        XCTAssertEqual(Array(result.spkcache[3..<6]), [0.5, 0.5, 0.5])
        XCTAssertEqual(Array(result.spkcachePreds[2..<4]), [0, 0])

        // Entry 2: frame 2 (not disabled)
        XCTAssertEqual(Array(result.spkcache[6..<9]), [7, 8, 9])
        XCTAssertEqual(Array(result.spkcachePreds[4..<6]), [0.1, 0.9])
    }

    // MARK: - updateSilenceProfile

    func testUpdateSilenceProfile() {
        let embs: [Float] = [
            1.0, 2.0, 3.0, 4.0,   // f0: speech
            0.5, 0.5, 0.5, 0.5,   // f1: silence
            2.0, 3.0, 4.0, 5.0,   // f2: speech
            0.1, 0.2, 0.3, 0.4,   // f3: silence
        ]
        let preds: [Float] = [
            0.8, 0.1,   // f0: sum=0.9 → speech
            0.05, 0.05, // f1: sum=0.1 → silence
            0.7, 0.6,   // f2: sum=1.3 → speech
            0.05, 0.02, // f3: sum=0.07 → silence
        ]

        var meanSilEmb = [Float](repeating: 0, count: 4)
        var nSilFrames = 0

        AOSCCompressor.updateSilenceProfile(
            meanSilEmb: &meanSilEmb, nSilFrames: &nSilFrames,
            embSeq: embs, preds: preds,
            nNewFrames: 4, embDim: 4, nSpk: 2, silThreshold: 0.2)

        // Expected: mean of f1 and f3 embeddings
        // f1=[0.5,0.5,0.5,0.5], f3=[0.1,0.2,0.3,0.4]
        // mean = [0.3, 0.35, 0.4, 0.45]
        XCTAssertEqual(nSilFrames, 2)
        let expectedMean: [Float] = [0.3, 0.35, 0.4, 0.45]
        for d in 0..<4 {
            XCTAssertEqual(meanSilEmb[d], expectedMean[d], accuracy: 1e-5,
                           "Silence mean dim \(d): got \(meanSilEmb[d]), expected \(expectedMean[d])")
        }
    }

    func testUpdateSilenceProfileIncremental() {
        var meanSilEmb: [Float] = [1.0, 2.0]
        var nSilFrames = 2  // Existing 2 frames with mean [1.0, 2.0]

        // New frame that is silence: [3.0, 4.0]
        let embs: [Float] = [3.0, 4.0]
        let preds: [Float] = [0.05, 0.05]  // sum=0.1 < 0.2 → silence

        AOSCCompressor.updateSilenceProfile(
            meanSilEmb: &meanSilEmb, nSilFrames: &nSilFrames,
            embSeq: embs, preds: preds,
            nNewFrames: 1, embDim: 2, nSpk: 2, silThreshold: 0.2)

        XCTAssertEqual(nSilFrames, 3)
        // Old sum: [2.0, 4.0], new sum: [2.0+3.0, 4.0+4.0] = [5.0, 8.0]
        // New mean: [5.0/3, 8.0/3]
        XCTAssertEqual(meanSilEmb[0], 5.0 / 3.0, accuracy: 1e-5)
        XCTAssertEqual(meanSilEmb[1], 8.0 / 3.0, accuracy: 1e-5)
    }

    func testUpdateSilenceProfileNoSilence() {
        var meanSilEmb: [Float] = [1.0, 2.0]
        var nSilFrames = 1
        let embs: [Float] = [5.0, 6.0]
        let preds: [Float] = [0.8, 0.5]  // sum=1.3 > 0.2 → speech

        AOSCCompressor.updateSilenceProfile(
            meanSilEmb: &meanSilEmb, nSilFrames: &nSilFrames,
            embSeq: embs, preds: preds,
            nNewFrames: 1, embDim: 2, nSpk: 2, silThreshold: 0.2)

        XCTAssertEqual(nSilFrames, 1, "No new silence → count unchanged")
        XCTAssertEqual(meanSilEmb, [1.0, 2.0], "No new silence → mean unchanged")
    }

    // MARK: - Full Compression Pipeline (NeMo PyTorch ground truth)

    /// Load test cases from nemo_ground_truth.json generated by real NeMo code.
    private func loadNeMoGroundTruth() throws -> [[String: Any]] {
        // Try multiple paths (test runner CWD varies)
        let paths = [
            "Tests/SpeechVADTests/nemo_ground_truth.json",
            "nemo_ground_truth.json",
            "../Tests/SpeechVADTests/nemo_ground_truth.json",
        ]
        for path in paths {
            let url = URL(fileURLWithPath: path)
            if let data = try? Data(contentsOf: url),
               let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
               let cases = json["compress_cases"] as? [[String: Any]] {
                return cases
            }
        }
        throw XCTSkip("nemo_ground_truth.json not found — run scripts/definitive_verify.py to generate")
    }

    /// Verify full AOSC compress pipeline against NeMo PyTorch ground truth.
    /// Test vectors use unique prediction values (no ties), so output must be
    /// bit-identical to NeMo's _compress_spkcache.
    func testCompressVsNeMoGroundTruth() throws {
        let cases = try loadNeMoGroundTruth()
        XCTAssertGreaterThanOrEqual(cases.count, 4, "Need at least 4 test cases")

        for c in cases {
            let name = c["name"] as! String
            let nFrames = c["n_frames"] as! Int
            let nSpk = c["n_spk"] as! Int
            let embDim = c["emb_dim"] as! Int
            let spkcacheLen = c["spkcache_len"] as! Int
            let silFrames = c["sil_frames"] as! Int
            let preds = (c["preds"] as! [NSNumber]).map { Float(truncating: $0) }
            let embs = (c["embs"] as! [NSNumber]).map { Float(truncating: $0) }
            let meanSil = (c["mean_sil"] as! [NSNumber]).map { Float(truncating: $0) }
            let expectedEmbs = (c["expected_embs"] as! [NSNumber]).map { Float(truncating: $0) }
            let expectedPreds = (c["expected_preds"] as! [NSNumber]).map { Float(truncating: $0) }

            let config = SortformerConfig(
                spkcacheLen: spkcacheLen, fcDModel: embDim, maxSpeakers: nSpk,
                spkcacheSilFramesPerSpk: silFrames)

            let result = AOSCCompressor.compress(
                embSeq: embs, preds: preds,
                nFrames: nFrames, meanSilEmb: meanSil, config: config)

            // Verify every embedding value
            XCTAssertEqual(result.spkcache.count, expectedEmbs.count,
                           "\(name): embedding count mismatch")
            for i in 0..<expectedEmbs.count {
                XCTAssertEqual(result.spkcache[i], expectedEmbs[i], accuracy: 1e-5,
                               "\(name) emb[\(i)]: swift=\(result.spkcache[i]) nemo=\(expectedEmbs[i])")
            }

            // Verify every prediction value
            XCTAssertEqual(result.spkcachePreds.count, expectedPreds.count,
                           "\(name): prediction count mismatch")
            for i in 0..<expectedPreds.count {
                XCTAssertEqual(result.spkcachePreds[i], expectedPreds[i], accuracy: 1e-5,
                               "\(name) pred[\(i)]: swift=\(result.spkcachePreds[i]) nemo=\(expectedPreds[i])")
            }
        }
    }

    /// Verify mathematical properties of AOSC compression output.
    func testCompressProperties() throws {
        let cases = try loadNeMoGroundTruth()

        for c in cases {
            let name = c["name"] as! String
            let nSpk = c["n_spk"] as! Int
            let embDim = c["emb_dim"] as! Int
            let spkcacheLen = c["spkcache_len"] as! Int
            let silFrames = c["sil_frames"] as! Int
            let preds = (c["preds"] as! [NSNumber]).map { Float(truncating: $0) }
            let embs = (c["embs"] as! [NSNumber]).map { Float(truncating: $0) }
            let meanSil = (c["mean_sil"] as! [NSNumber]).map { Float(truncating: $0) }

            let config = SortformerConfig(
                spkcacheLen: spkcacheLen, fcDModel: embDim, maxSpeakers: nSpk,
                spkcacheSilFramesPerSpk: silFrames)

            let result = AOSCCompressor.compress(
                embSeq: embs, preds: preds,
                nFrames: c["n_frames"] as! Int, meanSilEmb: meanSil, config: config)

            // P1: Output has exactly spkcacheLen frames
            XCTAssertEqual(result.spkcache.count, spkcacheLen * embDim,
                           "\(name): wrong embedding size")
            XCTAssertEqual(result.spkcachePreds.count, spkcacheLen * nSpk,
                           "\(name): wrong prediction size")

            // P2: Silence frames have zero predictions and silence embedding
            for i in 0..<spkcacheLen {
                let predBase = i * nSpk
                let isSilence = (0..<nSpk).allSatisfy { result.spkcachePreds[predBase + $0] == 0 }
                if isSilence {
                    let embBase = i * embDim
                    for d in 0..<embDim {
                        XCTAssertEqual(result.spkcache[embBase + d], meanSil[d], accuracy: 1e-6,
                                       "\(name): silence frame \(i) should use mean silence embedding")
                    }
                }
            }

            // P3: Arrival-time ordering — within each speaker block, active speaker
            //     predictions should appear in order (speaker 0 block before speaker 1, etc.)
            var lastSpeaker = -1
            for i in 0..<spkcacheLen {
                let predBase = i * nSpk
                let isSilence = (0..<nSpk).allSatisfy { result.spkcachePreds[predBase + $0] == 0 }
                if !isSilence {
                    var dominantSpk = 0
                    var maxPred: Float = -1
                    for s in 0..<nSpk {
                        if result.spkcachePreds[predBase + s] > maxPred {
                            maxPred = result.spkcachePreds[predBase + s]
                            dominantSpk = s
                        }
                    }
                    if dominantSpk < lastSpeaker {
                        XCTFail("\(name): speaker order violation at frame \(i) — " +
                                "speaker \(dominantSpk) after speaker \(lastSpeaker)")
                    }
                    lastSpeaker = dominantSpk
                }
            }

            // P4: At least nSpk * silFrames silence frames (more if not enough active speakers)
            let silCount = (0..<spkcacheLen).filter { i in
                (0..<nSpk).allSatisfy { result.spkcachePreds[i * nSpk + $0] == 0 }
            }.count
            XCTAssertGreaterThanOrEqual(silCount, nSpk * silFrames,
                           "\(name): expected >= \(nSpk * silFrames) silence frames, got \(silCount)")
        }
    }

    // MARK: - Config Tests

    func testAOSCConfigDefaults() {
        let config = SortformerConfig.default
        XCTAssertEqual(config.spkcacheSilFramesPerSpk, 3)
        XCTAssertEqual(config.strongBoostRate, 0.75, accuracy: 0.001)
        XCTAssertEqual(config.weakBoostRate, 1.5, accuracy: 0.001)
        XCTAssertEqual(config.minPosScoresRate, 0.5, accuracy: 0.001)
        XCTAssertEqual(config.predScoreThreshold, 0.25, accuracy: 0.001)
        XCTAssertEqual(config.silThreshold, 0.2, accuracy: 0.001)
        XCTAssertEqual(config.scoresBoostLatest, 0.05, accuracy: 0.001)
        XCTAssertEqual(config.spkcacheUpdatePeriod, 188)
    }

    func testAOSCDerivedParameters() {
        let config = SortformerConfig.default
        let perSpk = config.spkcacheLen / config.maxSpeakers - config.spkcacheSilFramesPerSpk
        XCTAssertEqual(perSpk, 44)
        XCTAssertEqual(Int(floor(Float(perSpk) * config.strongBoostRate)), 33)
        XCTAssertEqual(Int(floor(Float(perSpk) * config.weakBoostRate)), 66)
        XCTAssertEqual(Int(floor(Float(perSpk) * config.minPosScoresRate)), 22)
    }

    // MARK: - Edge Cases

    func testCompressAllSilence() throws {
        // Verify all-silence case from NeMo ground truth
        let cases = try loadNeMoGroundTruth()
        guard let silCase = cases.first(where: { ($0["name"] as? String) == "all_silence" }) else {
            throw XCTSkip("all_silence case not found in ground truth")
        }

        let nFrames = silCase["n_frames"] as! Int
        let nSpk = silCase["n_spk"] as! Int
        let embDim = silCase["emb_dim"] as! Int
        let spkcacheLen = silCase["spkcache_len"] as! Int
        let silFrames = silCase["sil_frames"] as! Int
        let preds = (silCase["preds"] as! [NSNumber]).map { Float(truncating: $0) }
        let embs = (silCase["embs"] as! [NSNumber]).map { Float(truncating: $0) }
        let meanSil = (silCase["mean_sil"] as! [NSNumber]).map { Float(truncating: $0) }
        let expectedEmbs = (silCase["expected_embs"] as! [NSNumber]).map { Float(truncating: $0) }

        let config = SortformerConfig(
            spkcacheLen: spkcacheLen, fcDModel: embDim, maxSpeakers: nSpk,
            spkcacheSilFramesPerSpk: silFrames)

        let result = AOSCCompressor.compress(
            embSeq: embs, preds: preds,
            nFrames: nFrames, meanSilEmb: meanSil, config: config)

        // All frames should use mean silence embedding
        for i in 0..<expectedEmbs.count {
            XCTAssertEqual(result.spkcache[i], expectedEmbs[i], accuracy: 1e-5,
                           "all_silence emb[\(i)]")
        }

        // All predictions should be zero
        for v in result.spkcachePreds {
            XCTAssertEqual(v, 0.0, accuracy: 1e-6, "all_silence: predictions should be zero")
        }
    }
}
